FROM liquibase/liquibase:4.7.1

COPY ./db/seeding/*.gz /liquibase/db/seeding/
COPY ./db/seeding/*.xml /liquibase/db/seeding/
COPY ./db/changelog /liquibase/db/changelog

COPY liquibase-postgresql-4.7.1.jar /liquibase/lib/

CMD ["sh", "-c", "docker-entrypoint.sh --url=${DB_URL} --username=${DB_USERNAME} --password=${DB_PASSWORD} --classpath=/liquibase --changeLogFile=db/changelog/db.changelog-master.xml --logLevel=info update"]