apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-configmap
  namespace: postgres-operator
  labels:
    name: spring-configmap
data:
  default-config.json: |-
    {
      "postgres.url": "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}",
      "postgres.username": "${DB_USERNAME}",
      "postgres.password": "${DB_PASSWORD}"
    }