apiVersion: v1
kind: Service
metadata:
  name: spring-svc
  namespace: postgres-operator
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: spring
  ports:
    - name: spring-port
      protocol: TCP
      port: 8080
      targetPort: 8080