apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring
  namespace: postgres-operator
  labels:
    app.kubernetes.io/name: spring
    app.kubernetes.io/version: v2
    app.kubernetes.io/component: application
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: spring
      app.kubernetes.io/version: v2
      app.kubernetes.io/component: application
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spring
        app.kubernetes.io/version: v2
        app.kubernetes.io/component: application
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/name: pgpool
              topologyKey: kubernetes.io/hostname
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: spring
                    app.kubernetes.io/version: v2
      containers:
        - name: spring
          image: coenvk/spring-zero-downtime-poc:v2
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              value: 'pgpool-svc.postgres-operator.svc'
            - name: DB_PORT
              value: '9999'
            - name: DB_DATABASE
              valueFrom: { secretKeyRef: { name: hippo-pguser-hippo, key: dbname } }
            - name: DB_USERNAME
              valueFrom: { secretKeyRef: { name: hippo-pguser-hippo, key: user } }
            - name: DB_PASSWORD
              valueFrom: { secretKeyRef: { name: hippo-pguser-hippo, key: password } }
            - name: DB_URL
              value: 'jdbc:postgresql://$(DB_HOST):$(DB_PORT)/$(DB_DATABASE)'
            - name: SPRING_PROFILES_ACTIVE
              value: default
            - name: SPRING_APPLICATION_JSON
              value: '{ "postgres.url": "$(DB_URL)", "postgres.username": "$(DB_USERNAME)", "postgres.password": "$(DB_PASSWORD)" }'