apiVersion: v1
kind: Service
metadata:
  name: pgpool-svc
  namespace: postgres-operator
spec:
  selector:
    app.kubernetes.io/name: pgpool
  ports:
    - name: pgpool-port
      protocol: TCP
      port: 9999
      targetPort: 9999
  topologyKeys:
    - "kubernetes.io/hostname"
    - "topology.kubernetes.io/zone"
    - "topology.kubernetes.io/region"
    - "*"