apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgpool
  namespace: postgres-operator
  labels:
    app.kubernetes.io/name: pgpool
    app.kubernetes.io/component: application
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: pgpool
      app.kubernetes.io/component: application
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pgpool
        app.kubernetes.io/component: application
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: pgpool
      containers:
        - name: pgpool
          image: coenvk/pgpool:latest
          imagePullPolicy: "IfNotPresent"
          env:
            - name: DB_USERNAME
              valueFrom: { secretKeyRef: { name: hippo-pguser-hippo, key: user } }
            - name: DB_PASSWORD
              valueFrom: { secretKeyRef: { name: hippo-pguser-hippo, key: password } }
            - name: PGPOOL_USERNAME
              valueFrom: { secretKeyRef: { name: pgpool-secret, key: PGPOOL_USER } }
            - name: PGPOOL_PASSWORD
              valueFrom: { secretKeyRef: { name: pgpool-secret, key: PGPOOL_PASSWORD } }
            - name: PGPOOL_PARAMS_AUTH_METHOD
              value: scram-sha-256
            - name: POSTGRES_USERNAME
              valueFrom: { secretKeyRef: { name: hippo-pguser-postgres, key: user } }
            - name: POSTGRES_PASSWORD
              valueFrom: { secretKeyRef: { name: hippo-pguser-postgres, key: password } }
            - name: TPCC_USERNAME
              valueFrom: { secretKeyRef: { name: tpcc-secret, key: TPCC_USER } }
            - name: TPCC_PASSWORD
              valueFrom: { secretKeyRef: { name: tpcc-secret, key: TPCC_PASSWORD } }
          volumeMounts:
            - name: pgpool-configmap
              mountPath: /config
      volumes:
        - name: pgpool-configmap
          configMap:
            name: pgpool-configmap