apiVersion: v1
kind: Service
metadata:
  name: pgpool-svc
  namespace: postgres-operator
  annotations:
    service.kubernetes.io/topology-aware-hints: auto
spec:
  selector:
    app.kubernetes.io/name: pgpool
  ports:
    - name: pgpool-port
      protocol: TCP
      port: 9999
      targetPort: 9999