apiVersion: v1
kind: ConfigMap
metadata:
  name: pgpool-configmap
  namespace: postgres-operator
  labels:
    name: pgpool-configmap
data:
  pgpool.conf: |-
    listen_addresses = '*'
    port = 9999
    socket_dir = '/var/run/pgpool'
    pcp_listen_addresses = '*'
    pcp_port = 9898
    pcp_socket_dir = '/var/run/pgpool'

    backend_hostname0 = 'hippo-primary.postgres-operator.svc'
    backend_port0 = 5432
    backend_weight0 = 1
    backend_flag0 = 'ALWAYS_PRIMARY|DISALLOW_TO_FAILOVER'

    backend_hostname1 = 'hippo-replicas.postgres-operator.svc'
    backend_port1 = 5432
    backend_weight1 = 1
    backend_flag1 = 'DISALLOW_TO_FAILOVER'

    enable_pool_hba = on
    backend_clustering_mode = 'streaming_replication'
    num_init_children = 32
    max_pool = 4
    child_life_time = 300
    child_max_connections = 0
    connection_life_time = 0
    client_idle_limit = 0
    connection_cache = on
    load_balance_mode = on
    ssl = on
    failover_on_backend_error = off
  pool_hba.conf: |-
    local   all         all                               trust
    host    all         all         127.0.0.1/32          trust
    host    all         all         ::1/128               trust
    host    all         pgpool      0.0.0.0/0             scram-sha-256
    host    all         postgres    0.0.0.0/0             scram-sha-256
    host    replication all         0.0.0.0/0             scram-sha-256
    hostssl all         all         0.0.0.0/0             scram-sha-256
