apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: hippo
  namespace: postgres-operator
  labels:
    app.kubernetes.io/name: hippo
    app.kubernetes.io/component: database
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:centos8-14.1-0
  postgresVersion: 14
  users:
    - name: postgres
    - name: hippo
      databases:
        - hippo
  instances:
    - name: instance1
      replicas: 3
      dataVolumeClaimSpec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 2Gi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    postgres-operator.crunchydata.com/cluster: hippo
                    postgres-operator.crunchydata.com/instance-set: instance1
                    app.kubernetes.io/component: application
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.36-0
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              accessModes:
                - "ReadWriteOnce"
              resources:
                requests:
                  storage: 1Gi
#  monitoring:
#    pgmonitor:
#      exporter:
#        image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.0.4-0

  patroni:
    dynamicConfiguration:
      # synchronous_mode: true
      # synchronous_mode_strict: true
      postgresql:
        parameters:
          synchronous_commit: off
          shared_buffers: 20GB
          max_connections: 128
          min_wal_size: 2GB
          max_wal_size: 20GB
          maintenance_work_mem: 32MB
          checkpoint_timeout: 1h
          checkpoint_completion_target: 1
          checkpoint_warning: 0
          log_checkpoints: off
          logging_collector: off
          autovacuum: off
          autovacuum_work_mem: -1
          wal_buffers: 512MB
          max_stack_depth: 2MB
          work_mem: 512MB
          temp_buffers: 512MB
          max_locks_per_transaction: 64
          max_pred_locks_per_transaction: 64
          wal_level: replica
