apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  labels:
    app: postgres
    role: service
spec:
  type: ClusterIP
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
    protocol: TCP
  selector:
    app: postgres