apiVersion: v1
kind: Service
metadata:
  name: postgres-replicas-svc
  labels:
    app: postgres-replicas
    role: service
spec:
  type: ClusterIP
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
      protocol: TCP
  selector:
    app: postgres-replicas