apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-replicas-statefulset
spec:
  serviceName: postgres-replicas-svc
  replicas: 2
  selector:
    matchLabels:
      app: postgres-replicas
  template:
    metadata:
      labels:
        app: postgres-replicas
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: "IfNotPresent"
          envFrom:
            - secretRef:
                name: postgres-secret
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: "scram-sha-256"
            - name: POSTGRES_INITDB_ARGS
              value: "--auth-host=scram-sha-256"
            - name: PGDATA
              value: "/var/lib/postgresql/data"
          ports:
            - name: postgresql
              containerPort: 5432
              protocol: TCP
          volumeMounts:
            - name: postgresdb
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: postgres-pv-claim